name: mysql 
description: docker compose for Mysql 
keywords: docker, compose, Mysql
service:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_mysql_database_name
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql