import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import React from 'react';
import Editor from '@monaco-editor/react';
import postgres from '../../composes/postgres';
import redis from '../../composes/redis';
import { Listbox } from '@headlessui/react';
import ServiceSelector from '@/component/ServiceSelector';

export default function Home() {
  React.useEffect(() => {}, []);
  const people = [
    { id: 1, name: 'Durward Reynolds', unavailable: false },
    { id: 2, name: 'Kenton Towne', unavailable: false },
    { id: 3, name: 'Therese Wunsch', unavailable: false },
    { id: 4, name: 'Benedict Kessler', unavailable: true },
    { id: 5, name: 'Katelyn Rohan', unavailable: false },
  ];

  const editorRef = React.useRef(null);
  const [content, setContent] = React.useState('');

  function handleEditorDidMount(editor: any, monaco: any) {
    editorRef.current = editor;
    setContent(postgres + redis);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ServiceSelector />
        <div className="relative w-full h-60 mt-12 -z-0">
          <Editor
            theme="vs-dark"
            language="yaml"
            defaultLanguage="yaml"
            onMount={handleEditorDidMount}
            value={content}
          />
        </div>
      </main>
    </>
  );
}
